version: '3.8'
services:
  db:
    container_name: postgresql-weather
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: segments_service
    volumes:
      - "${POSTGRES_VOLUME}:/var/lib/postgresql/data"
    ports:
      - "${POSTGRES_PORT_DST}:${POSTGRES_PORT_SRC}"
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4-weather
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_USER
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
    volumes:
      - "${PGADMIN_VOLUME}:/var/lib/pgadmin"
    networks:
      - backend


networks:
  backend:
    driver: bridge